# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"



formats:
  - pdf
requirements_file: requirements.txt
python:
  pip_install: true
  extra_requirements:
    - tests
    - docs
